spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: sean
    url: jdbc:mysql://xiaojs.vip:3306/sean_app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    publisher-confirms: true
#    publisher-returns: true
#  redis:
#    host: xiaojs.vip
#    database: 0
#    port: 6379
#    password:
#  cache:
#    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
#fastdfs:
#  nginx:
#    host: http://127.0.0.1/